# Flatpak build environment image
# This image contains all tools and runtimes needed to build the lv Flatpak.
# Actual build is run via: podman run --privileged (see scripts/flatpak-build.sh)
#
# Build env image:
#   TMPDIR=~/.buildah-tmp podman build -f docker/Dockerfile.flatpak -t lv-flatpak-env .
# Run build:
#   ./scripts/flatpak-build.sh

FROM registry.fedoraproject.org/fedora:41

RUN dnf install -y \
    flatpak \
    flatpak-builder \
    python3 \
    python3-pip \
    git \
    curl \
    bubblewrap \
    ostree \
    && dnf clean all

# Add flathub remote
RUN flatpak --user remote-add --if-not-exists flathub \
    https://dl.flathub.org/repo/flathub.flatpakrepo

# Install required runtime + SDK + Rust extension
RUN flatpak --user install -y flathub \
    org.freedesktop.Platform//24.08 \
    org.freedesktop.Sdk//24.08 \
    org.freedesktop.Sdk.Extension.rust-stable//24.08

# Pre-install cargo generator deps
RUN pip3 install --quiet aiohttp toml tomlkit && \
    curl -fsSL -o /usr/local/bin/flatpak-cargo-generator.py \
      https://raw.githubusercontent.com/flatpak/flatpak-builder-tools/master/cargo/flatpak-cargo-generator.py
