#!/bin/bash
# Write repo-local native env config for make targets.
# Usage:
#   bash scripts/configure-native.sh
#   LV_NATIVE_PREFIXES=/opt/foo:/opt/bar bash scripts/configure-native.sh
set -euo pipefail

cd "$(dirname "$0")/.."

out="${CONFIG_MK:-config.local.mk}"
prefixes="${LV_NATIVE_PREFIXES:-}"

if [ -z "$prefixes" ] && command -v brew >/dev/null 2>&1; then
    prefixes="$(brew --prefix)"
fi

{
    echo "# Autogenerated by scripts/configure-native.sh"
    echo "# Commit ignored. Regenerate when local native library prefix changes."
    echo "LV_NATIVE_PREFIXES := $prefixes"
} > "$out"

echo "wrote $out"
