#!/bin/bash
# Detect native C library prefix and write build config files.
# Usage:
#   bash scripts/configure.sh
#   LV_NATIVE_PREFIXES=/opt/foo:/opt/bar bash scripts/configure.sh
set -euo pipefail

cd "$(dirname "$0")/.."

# ── Detect prefixes ──────────────────────────────────────────────────
prefixes=()
if [ -n "${LV_NATIVE_PREFIXES:-}" ]; then
    IFS=':' read -r -a prefixes <<< "${LV_NATIVE_PREFIXES}"
elif command -v brew >/dev/null 2>&1; then
    prefixes+=("$(brew --prefix)")
fi

if [ "${#prefixes[@]}" -eq 0 ]; then
    echo "configure: no brew or LV_NATIVE_PREFIXES found, skipping .cargo/config.toml"
    cat > config.local.mk <<'LOCAL'
# Autogenerated by scripts/configure.sh
# Commit ignored. Regenerate when local native library prefix changes.
# (no brew — using system default paths)
LOCAL
    exit 0
fi

# ── Compute paths ────────────────────────────────────────────────────
pkg_config_paths=()
lib_paths=()
for prefix in "${prefixes[@]}"; do
    pkg_config_paths+=(
        "$prefix/opt/sdl2/lib/pkgconfig"
        "$prefix/opt/mpv/lib/pkgconfig"
        "$prefix/opt/xorgproto/share/pkgconfig"
        "$prefix/opt/libx11/lib/pkgconfig"
        "$prefix/opt/libxext/lib/pkgconfig"
        "$prefix/opt/libxrandr/lib/pkgconfig"
        "$prefix/opt/libxfixes/lib/pkgconfig"
    )
    lib_paths+=(
        "$prefix/opt/sdl2/lib"
        "$prefix/opt/mpv/lib"
    )
done

# collapse with colon separator
join_by() { local IFS=':'; printf '%s' "$*"; }
pkg_config_path=$(join_by "${pkg_config_paths[@]}")
lib_path=$(join_by "${lib_paths[@]}")

# ── Write config.local.mk (for Make) ──────────────────────────────────
{
    echo "# Autogenerated by scripts/configure.sh"
    echo "# Commit ignored. Regenerate when local native library prefix changes."
    echo "LV_NATIVE_PREFIXES := $(join_by "${prefixes[@]}")"
} > config.local.mk
echo "wrote config.local.mk"

# ── Write .cargo/config.toml (for cargo, rust-analyzer) ───────────────
mkdir -p .cargo
cat > .cargo/config.toml <<EOF
# Autogenerated by scripts/configure.sh
# Commit ignored. Regenerate when local native library prefix changes.
[env]
PKG_CONFIG_PATH = "${pkg_config_path}"
LIBRARY_PATH = "${lib_path}"
LD_LIBRARY_PATH = "${lib_path}"
EOF
echo "wrote .cargo/config.toml"
